USE [SPIF]
GO

/****** Object:  Table [SPIF_team].[MB_TBL_CLNT_UNITS_APJ]    Script Date: 6/4/2026 6:56:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SPIF_team].[MB_TBL_CLNT_UNITS_APJ](
	[SR_BADGE] [float] NOT NULL,
	[Sales_BU_ID] [nvarchar](20) NULL,
	[CSPG_CLNT_QTY] [float] NULL,
	[QUARTER_ID] [nvarchar](20) NULL,
	[MONTH] [nvarchar](50) NULL,
	[WEEK] [nvarchar](50) NULL,
	[UPDATE_COMMENT] [nvarchar](255) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATED_BY] [sysname] NOT NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATED_BY] [sysname] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [SPIF_team].[MB_TBL_CLNT_UNITS_APJ] ADD  CONSTRAINT [CREATED_DATE_CLNT_NEW]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

ALTER TABLE [SPIF_team].[MB_TBL_CLNT_UNITS_APJ] ADD  CONSTRAINT [CREATED_USER_CLNT_NEW]  DEFAULT (suser_sname()) FOR [CREATED_BY]
GO

ALTER TABLE [SPIF_team].[MB_TBL_CLNT_UNITS_APJ] ADD  CONSTRAINT [UPDATED_DATE_CLNT_NEW]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO

ALTER TABLE [SPIF_team].[MB_TBL_CLNT_UNITS_APJ] ADD  CONSTRAINT [UPDATED_USER_CLNT_NEW]  DEFAULT (suser_sname()) FOR [UPDATED_BY]
GO


