USE [SPIF]
GO

/****** Object:  View [SPIF_team].[VW_APJ_SW_UNITS_PAYOUT_FINAL]    Script Date: 7/12/2026 5:25:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [SPIF_team].[VW_APJ_SW_UNITS_PAYOUT_FINAL]
AS
SELECT AR.QUARTER_ID, AR.RPT_QUEUE, AR.SR_BADGE, AR.SR_NAME, AR.RPT_ROLE, AR.System_qty, AR.Item_qty, AR.SW_AR, AR.VENDOR_NAME, Goal.GOAL_T1, Goal.GOAL_T2, Goal.GOAL_T3, Goal.GOAL_TYPE, 
                  CASE WHEN AR.[RPT_ROLE] = 'ISR' AND Goal.GOAL_T1 > 0 AND [SW_AR] >= Goal.GOAL_T1 AND AR.Payout >= 600 THEN 600
				  WHEN AR.[RPT_ROLE] = 'ISR' AND Goal.GOAL_T1 > 0 AND [SW_AR] >= Goal.GOAL_T1 AND   AR.Payout < 600 THEN AR.Payout 
				  WHEN AR.[RPT_ROLE] = 'MGR' AND Goal.GOAL_T3 > 0 AND [SW_AR] >= Goal.GOAL_T3 THEN Goal.PAY_T3
				  WHEN AR.[RPT_ROLE] = 'MGR' AND Goal.GOAL_T2 > 0 AND [SW_AR] >= Goal.GOAL_T2 THEN Goal.PAY_T2 
				  WHEN AR.[RPT_ROLE] = 'MGR' AND Goal.GOAL_T1 > 0 AND [SW_AR] >= Goal.GOAL_T1 THEN Goal.PAY_T1 
				  WHEN AR.[RPT_ROLE] = 'RSM' AND Goal.GOAL_T3 > 0 AND [SW_AR] >= Goal.GOAL_T3 THEN Goal.PAY_T3
				  WHEN AR.[RPT_ROLE] = 'RSM' AND Goal.GOAL_T2 > 0 AND [SW_AR] >= Goal.GOAL_T2 THEN Goal.PAY_T2 
				  WHEN AR.[RPT_ROLE] = 'RSM' AND Goal.GOAL_T1 > 0 AND [SW_AR] >= Goal.GOAL_T1 THEN Goal.PAY_T1 
				  WHEN AR.[RPT_ROLE] = 'DIR' AND Goal.GOAL_T3 > 0 AND [SW_AR] >= Goal.GOAL_T3 THEN Goal.PAY_T3
				  WHEN AR.[RPT_ROLE] = 'DIR' AND Goal.GOAL_T2 > 0 AND [SW_AR] >= Goal.GOAL_T2 THEN Goal.PAY_T2 
				  WHEN AR.[RPT_ROLE] = 'DIR' AND Goal.GOAL_T1 > 0 AND [SW_AR] >= Goal.GOAL_T1 THEN Goal.PAY_T1
				  WHEN AR.[RPT_ROLE] = 'COACH' AND Goal.GOAL_T3 > 0 AND [SW_AR] >= Goal.GOAL_T3 THEN Goal.PAY_T3
				  WHEN AR.[RPT_ROLE] = 'COACH' AND Goal.GOAL_T2 > 0 AND [SW_AR] >= Goal.GOAL_T2 THEN Goal.PAY_T2
				  WHEN AR.[RPT_ROLE] = 'COACH' AND Goal.GOAL_T1 > 0 AND [SW_AR] >= Goal.GOAL_T1 THEN Goal.PAY_T1 ELSE 0 END AS Payout,
                      (SELECT Submission_Code
                       FROM      SPIF_team.MB_TBL_BUDGET_APJ_AR AS b
                       WHERE   (AR.RPT_QUEUE = RPT_QUEUE) AND (AR.VENDOR_NAME = VENDOR_NAME)) AS SUBMISSION_CODE
FROM     SPIF_team.VW_APJ_SW_UNITS_PAYOUT_TOTAL_AR AS AR LEFT OUTER JOIN
                  SPIF_team.MB_TBL_APJ_RPT_GOAL AS Goal ON Goal.QUARTER_ID = AR.QUARTER_ID AND Goal.RPT_QUEUE = AR.RPT_QUEUE AND Goal.RPT_ROLE = AR.RPT_ROLE AND Goal.VENDOR_NAME = AR.VENDOR_NAME
GO


